nodejs: Make prune_sources execute at do_patch phase
Fixes:
  ERROR: nodejs-22.21.1-r0 do_patch: Applying patch '0001-deps-disable-io_uring-support-in-libuv.patch' on target directory '/build/tmp/work/core2-32-poky-linux/nodejs/22.21.1/sources/node-v22.21.1'
  CmdError('quilt --quiltrc /build/tmp/work/core2-32-poky-linux/nodejs/22.21.1/recipe-sysroot-native/etc/quiltrc push', 0, "stdout: Applying patch 0001-deps-disable-io_uring-support-in-libuv.patch
  can't find file to patch at input line 27

The sources which related to libuv as deps/uv/ are removed in prune_sources
when depends on libuv.

So postpone prune_sources execute at do_patch phase to fix the gap.

Signed-off-by: Mingli Yu <mingli.yu@windriver.com>
Signed-off-by: Khem Raj <raj.khem@gmail.com>
Upstream-Hash: 60c3b8fb4fa46ab4beb1c749296556c12189c222
Upstream-Url: https://git.openembedded.org/meta-openembedded/commit/?id=60c3b8fb4fa46ab4beb1c749296556c12189c222
Upstream-GitHub: https://github.com/openembedded/meta-openembedded/commit/60c3b8fb4fa46ab4beb1c749296556c12189c222